[project]
name = "dtsa5304"
version = "0.1.0"
description = "Final project for DTSA 5304 - Fundamentals of Data Visualization"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=6.2.2",
    "itables>=2.9.1",
    "jupyter>=1.1.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scipeds>=0.0.8",
]

[build-system]
requires = ["uv-build>=0.5.0"]
build-backend = "uv_build"
