---
title: The Rise of Computer Science
author: Trey Hendrix
date: last-modified
format: 
    html:
        embed-resources: true
        toc: true
---

# Introduction

My data visualization project leverages the Integrated Postsecondary Education Data System (IPEDS) dataset to answer the question: **when did computer science (CS) become such a popular undergraduate degree, and how has its popularity varied geographically?**

This question is motivated and informed by the previous data projects I have worked on as part of my job in higher education administration. Of course, the "learn-to-code" phenomenon is a ubiquitous topic in higher education. Yet, I was still surprised to see the dramatic national trend in CS degrees in the dataset.

Furthermore, as part of my previous IPEDS data project, I struggled to visualize the rich, degrees-granted IPEDS dataset efficiently. I wanted to maximize users' freedom to discover trends in the data across institutions. However, many visualizations used line plots, with multiple institutions shown in different colors, producing a "rainbow spaghetti" effect that obscured trends and likely discouraged exploration. Thus, for this project, I wanted to begin with a more focused question and a better understanding of effective visualization design, informed by Dr. Albers Szafir’s lectures. A toy example of the "rainbow spaghetti" problem is below (after some Python setup):

```{python}
# | label: external-modules
from datetime import datetime
from zoneinfo import ZoneInfo

import altair as alt
from itables import show
from vega_datasets import data
```

```{python}
# | label: local-modules
from dtsa5304.etl import get_ipeds_data, get_rainbow_spaghetti_data
from dtsa5304.util import find_project_dir
from dtsa5304.ref import fips_map, state_to_region_map
```

```{python}
# | label: rainbow-spaghetti
pasta_selection = alt.selection_point(fields=["pasta"], bind="legend")
rainbow_pasta_plot = (
    alt.Chart(get_rainbow_spaghetti_data())
    .mark_line(point=True)
    .encode(
        x=alt.X("year:Q", axis=alt.Axis(format="d"), title="Year"),
        y=alt.Y("prop:Q", axis=alt.Axis(format="%"), title="Made-up Proportion"),
        color=alt.Color(
            "pasta:N", title="Pasta Shape", scale=alt.Scale(scheme="tableau10")
        ),
        tooltip=[
            alt.Tooltip("pasta:N", title="Pasta Shape"),
            alt.Tooltip("year:Q", title="Year"),
            alt.Tooltip("prop:Q", title="Made-up Proportion", format=".2%"),
        ],
        opacity=alt.condition(pasta_selection, alt.value(1), alt.value(0.2)),
    )
    .properties(
        width=500, height=400, title="Rainbow Spaghetti - Fake Data Shown Badly"
    )
    .add_params(pasta_selection)
)

rainbow_pasta_plot.show()
```

# Data Information

IPEDS is an annual data collection project conducted by the US Department of Education that gathers information from every college that participates in federal student aid programs (virtually all institutions). To answer our question about computer science, we are more interested in the IPEDS Completions component, which tracks degrees awarded using a special taxonomy that lets us compare apples-to-apples across institutions. We will use the "Computer Science" NCSES detailed field group to ensure that we collect information on many degrees that may not be simply named "Computer Science Major."

To import these data, I leverage the excellent `scipeds` package, which utilizes a DuckDB framework. For details, please see the script `src/dtsa5304/etl.py` in [the project's GitHub repository](https://github.com/treyhendrix/dtsa5304).

```{python}
# | label: ipeds-etl
prop_cs_df = get_ipeds_data()
```

Our basic dataset is fairly simple: for each non-profit or public institution in the IPEDS database, we have yearly counts of Bachelor's degrees and Computer Science Bachelor's degrees. The dataset is fairly large, with `{python} f"{prop_cs_df.shape[0]:,}"` rows, so I will show only the largest (by Bachelor's degrees awarded) institution in each state below for the latest survey year:

```{python}
# | label: state-sample
sample_prop_cs_df = (
    prop_cs_df.sort_values(
        ["state_abbreviation", "year", "bachelors_degrees"], ascending=[True, False, False]
    )
    .groupby("state_abbreviation")
    .head(1)
)
show(sample_prop_cs_df, showIndex=False)
```

Descriptive statistics for the numeric columns: 

```{python}
# | label: num-col-stats
num_col_stats_df = prop_cs_df.drop(columns="unitid").describe()
show(num_col_stats_df)
```

# Goals and Tasks

The project aims to address two complementary questions with the IPEDS dataset: 

1. When did CS become such a popular undergraduate degree?
2. How has the popularity varied geographically?

To accomplish these goals without creating "rainbow spaghetti", I will design my visualizations with the following task in mind: **I will focus on the state-level of detail in our dataset, and allow users to find large-scale patterns between states (e.g., identify states with similar trends) while also navigating between states and identifying small-scale patterns (e.g., change over time within a state).**

Using the task taxonomy that we learned in lecture, we can break this task down into the following components: 

1. Purpose: Explore the IPEDS dataset and confirm (or challenge) the "rise of CS" phenomenon
2. Means: Users navigate among states and cross reference a nationwide summary of the data. Users compare one state to another in an order that makes sense to them.
3. Data Characteristics: the task seeks to understand how the distribution of CS degrees has changed over time and space. On a low-level, we are comparing time series between states. 
4. Target Data: States are compared and data are normalized to be proportions (CS bachelor's degrees / total bachelor's degrees).
5. Workflow: Users identify outliers or clumps of related states, investigate the per-state trends, snowballing additional questions about the dataset. 
6. Roles: I have designed the visualizations for a general audience, but the visualization is implicitly geared towards Americans, or those familiar with US geography since the visualization is less meaningful without that context. 

# Visualizations

To visualize geographic trends in these data, we will summarize the data at the state-year level: 

```{python}
# | label: state-year-roll-up

state_year_df = (
    prop_cs_df.groupby(["year", "state_abbreviation"])
    .agg({"cs_bachelors_degrees": "sum", "bachelors_degrees": "sum"})
    .reset_index()
)
state_year_df["prop_cs"] = (
    state_year_df["cs_bachelors_degrees"] / state_year_df["bachelors_degrees"]
)

state_year_df["prop_desc"] = state_year_df.apply(
    lambda row: f"{row['cs_bachelors_degrees']:,.0f} of {row['bachelors_degrees']:,.0f} degrees", 
    axis=1,
)
```

```{python}
# | label: validate date range

# Confirm that all states in our map have min date = 1984 and max date = 2024 (stated in the report text)
state_max_min_year_df = (
    state_year_df.groupby("state_abbreviation")
    .agg(min_year=("year", "min"), max_year=("year", "max"))
    .reset_index()
)

unexpected_range_states_df = state_max_min_year_df.loc[
    (state_max_min_year_df["state_abbreviation"].isin(state_to_region_map))
    & (
        (state_max_min_year_df["min_year"] != 1984)
        | (state_max_min_year_df["max_year"] != 2024)
    )
]
if not unexpected_range_states_df.empty:
    raise ValueError(
        f"{unexpected_range_states_df.shape[0]} state(s) detected with unexpected date ranges."
    )
```

Now, we have a much more manageable `{python} f"{state_year_df.shape[0]:,}"` rows of data. However, viewing 50+ trend lines is still in the realm of "rainbow spaghetti." To get these data on a 2-D map, we need to arrive at a single metric for each state. 

Since our research question involves the "rise of CS", we can ask: where has the percentage of CS degrees changed the most over the course of our dataset (i.e., from `{python} str(state_year_df["year"].min())` to `{python} str(state_year_df["year"].max())`). 

```{python}
# | label: prop-change
sorted_grouped_state_year_df = state_year_df.sort_values(
    by=["state_abbreviation", "year"]
).groupby("state_abbreviation")

all_time_prop_change_df = (
    sorted_grouped_state_year_df["prop_cs"].last()
    - sorted_grouped_state_year_df["prop_cs"].first()
).reset_index(name="prop_cs_change")
```

```{python}
# | label: saving-plots-setup

PROJECT_DIR = find_project_dir()
PLOTS_DIR = PROJECT_DIR / "plots"
```

## Map Dashboard
```{python}
# | label: map-setup

# Add 2-digit FIPS id column to our IPEDS data
all_time_prop_change_df["fips"] = (
    all_time_prop_change_df["state_abbreviation"].map(fips_map).astype(int)
)  # The data source below drops leading zeros

states = alt.topo_feature(data.us_10m.url, "states")

# To scale positive and negative values with a diverging palette
max_abs_change = all_time_prop_change_df["prop_cs_change"].abs().max()

click = alt.selection_point(
    name="click",
    fields=["state_abbreviation"],
    value=[{"state_abbreviation": "NJ"}],
    empty=False,
)

change_map = (
    alt.Chart(states)
    .mark_geoshape()
    .encode(
        color=alt.Color(
            "prop_cs_change:Q",
            scale=alt.Scale(
                scheme="redblue",
                domain=[-max_abs_change, max_abs_change],
                reverse=True,
            ),
            legend=alt.Legend(
                format="%",
                orient="top",
                offset=0,
                direction="horizontal",
                gradientLength=450,
                title="All-Time Change in Percent of Bachelor's Degrees Awarded in CS",
                titleOrient="top",
                titleAnchor="middle",
                titleLimit=450,
            ),
        ),
        tooltip=[
            alt.Tooltip("state_abbreviation:N", title="State"),
            alt.Tooltip("prop_cs_change:Q", title="Change", format=".2%"),
        ],
    )
    .transform_lookup(
        lookup="id",
        from_=alt.LookupData(
            data=all_time_prop_change_df,
            key="fips",
            fields=["prop_cs_change", "state_abbreviation"],
        ),
    )
    .properties(
        width=500,
        height=400,
    )
    .project(
        type="albersUsa"  # Note: The territories (e.g., Guam) are dropped here, unfortunately
    )
    .add_params(click)
)
```

```{python}
# | label: state-trend-plot

state_chart = (
    alt.Chart(state_year_df)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:Q", axis=alt.Axis(format="d"), title="Year"),
        y=alt.Y("prop_cs:Q", axis=alt.Axis(format="%"), title="Proportion"),
        color=alt.Color("state_abbreviation:N", title="State"),
        tooltip=[
            alt.Tooltip("state_abbreviation:N", title="State"),
            alt.Tooltip("year:Q", title="Year"),
            alt.Tooltip("prop_cs:Q", title="Proportion", format=".2%"),
            alt.Tooltip("prop_desc:N", title="Count"),
        ],
    )
    .transform_filter(click)
    .properties(
        width=500,
        height=200,
        title=alt.TitleParams(
            # Dynamic title via Vega expression
            text=alt.expr(
                "click.state_abbreviation && length(click.state_abbreviation) > 0 "
                "? (length(click.state_abbreviation) > 5 "
                "   ? join(slice(click.state_abbreviation, 0, 5), ', ') + ', ... Trend' "
                "   : join(click.state_abbreviation, ', ') + ' Trend') "
                ": 'Click Map to View Individual State Trends'"
            ),
            anchor="middle",
        ),
    )
)
```

```{python}
# | label: combined-dashboard
# | fig-cap: "Tip: Hold shift when clicking to select multiple states from the map."

dashboard = change_map & state_chart
dashboard.save(PLOTS_DIR / "map_dashboard.html")
dashboard.show()
```

While I was clicking around this map, I noted the diversity of trends among the states: 

* First, there are no strong regional patterns in the all time change metric, except potentially in the south, which I will investigate further below. 
* Second, most states follow a pattern where CS degrees decreased from a previous period of relative popularity early in the dataset (1980s and 1990s), there is a sharp increase and decrease shortly after 2000 (the famous "dot-com bubble"), and a steady fairly consistent increase to a global maximum from 2010 until the end of the dataset. 

## Regions Plot

Reviewing the map above, a natural question arises about whether different regions in the US have similar trends in CS degrees awarded. In the map, this would manifest as clumps of states having similar colors. In the per-state plot, we would notice neighboring states having a similar shape. However, a more thorough and direct way to approach this question is to aggregate the data into meaningful regions and plot the result on the same plot. To do this, I will use the four regions defined by the US census:

```{python}
# | label: regions-rollup

state_year_df["region"] = state_year_df["state_abbreviation"].map(state_to_region_map)

region_year_df = (
    state_year_df.groupby(["year", "region"])
    .agg(
        cs_bachelors_degrees=("cs_bachelors_degrees", "sum"),
        bachelors_degrees=("bachelors_degrees", "sum"),
    )
    .reset_index()
)  # Note: Territories are silently dropped here since they are not part of the census regions

region_year_df["prop_desc"] = region_year_df.apply(
    lambda row: f"{row['cs_bachelors_degrees']:,.0f} of {row['bachelors_degrees']:,.0f} degrees", 
    axis=1,
)

region_year_df["prop_cs"] = (
    region_year_df["cs_bachelors_degrees"] / region_year_df["bachelors_degrees"]
)
```

```{python}
# | label: region-plot
region_selection = alt.selection_point(fields=["region"], bind="legend")

region_chart = (
    alt.Chart(region_year_df)
    .mark_line(point=True)
    .encode(
        x=alt.X("year:Q", axis=alt.Axis(format="d"), title="Year"),
        y=alt.Y("prop_cs:Q", axis=alt.Axis(format="%"), title="Proportion"),
        color=alt.Color("region:N", title="Region"),
        tooltip=[
            alt.Tooltip("region:N", title="Region"),
            alt.Tooltip("year:Q", title="Year"),
            alt.Tooltip("prop_cs:Q", title="Proportion", format=".2%"),
            alt.Tooltip("prop_desc:N", title="Count")
        ],
        opacity=alt.condition(region_selection, alt.value(1), alt.value(0.2)),
    )
    .properties(
        width=500,
        height=400,
        title="Regional CS Trend",
    )
    .add_params(region_selection)
)

region_chart.save(PLOTS_DIR / "regions.html")
region_chart.show()
```

The different regions have a remarkably similar trend through time. Again, we see two peaks - one around 1985 and one in the early 2000s - and a steep and steady increase between 2010 and 2024. The baseline level for the Northeast does seem to be consistently higher than the other regions, but the difference is small, suggesting broad uniformity in the "rise of CS" across these regions. 

# Design Summary and Justification 

## Map Dashboard 

The hope is that this map will accomplish three of the seven types of interaction that we discussed in lecture: 

* Explore: click a state to see its individual trend. Additionally, hover over individual years in the linked line plot to view details such as the exact number of degrees granted in each state in each year. 
* Abstract/Elaborate: the color of a state on the map is a single summary statistic (all time change in the percent of CS degrees), but the linked line plot shows the complete shape of the metric over time. We called this "Overview + Detail" in lecture. 
* Filter: by default, the linked line plot only shows one state at a time.

Regarding the specific mappings and encodings, I selected a map because I wanted to display data from all 50 states, but navigating a list or legend with that many entries is often tedious. Assuming the user is familiar with US geography, the map provides an easy way to query the dataset and identify regional trends in all-time change. The choice of a choropleth (using color to communicate the main state-wide statistic) was a natural one since the states vary too much in size for other markings to be easy to see. I chose a diverging encoding for the legend since an overall decline (blue) or increase (red) in CS degrees was a meaningful pattern that I wanted to investigate. I took care to scale the color so that no change (0%) appears as white and -X and +X have comparable luminance in blue and red, respectively.

The state-specific plot is more straightforward, and I deliberately mapped fewer values to aesthetics. For example, I originally considered mapping the size of the points to the total number of degrees awarded; however, the result was too busy for my liking, so I restricted that information to the tooltips. I included both points and lines to make the tooltips more accessible. Mapping color to state allows users to select multiple to compare (by holding shift). 

## Regions Plot

I decided to make this visualization to interrogate an observation I had while making the map dashboard: computer science's popularity seemed to have increased only slightly or even decreased in the south, overall. The regions plot makes this implicit synthesis an explicit comparison, sacrificing the exploratory focus of the map dashboard for a fixed set of marks that illustrate few noticeable differences between the regions. In lecture, we learned that heavily interactive plots (like the map dashboard requiring clicking through states) require a high degree of user attention and memory. On the other hand, the regions plot captures the comparison that we want to make in the "gist" of the visualization (i.e., at a glance). The design of this plot was also heavily influenced by my desire to compare time series data without creating a "rainbow spaghetti" effect, which is hopefully mitigated by only having four series present in the plot and using a fairly standard categorical color palette.

# Final Evaluation Approach
For my final evaluation, I made a [Google Forms survey link](https://forms.gle/SHrje3VZM6T3vfyo9) geared towards a general audience to gauge the effectiveness of my visualizations. For recruitment, I relied on two pools of people: (1) my friends and family, who typically do not have a great deal of experience designing data visualizations, and (2) classmates/peers via InScribe. The survey presented my visualizations and asked 10 questions related to them. Ultimately, 6 participants filled it out. The responses and motivation for the questions are below (please note that the map dashboard is plot A in the survey while the region plot is plot B). 

1. On a scale of 1 to 10, how would you describe your level of comfort and experience working with data (1 = uncomfortable/minimal experience; 10 = very comfortable/experienced)? 
    + Motivation: Ensure that the visualizations are approachable to a general audience and determine if data professionals had different feedback 
    + Responses: Bimodal distribution with mostly data professionals weighing in (one user selected 2 and five users selected 8-10)
2. Plot A: Approximately how many states did you click on in the map to see individual states' trends? 
    + Motivation: Gauge how engaging the map design is 
    + Responses: three users selected 6 to 10; two users selected 11 to 15; one user selected more than 20
3. Plot A: On a scale of 1 to 10, how confident are you that you understand the statistic that determines the color of each state in the map (1 = not confident at all; 10 = very confident)? 
    + Motivation: I wanted to see if users understood the potentially confusing all time change statistic. 
    + Responses: Uniform distribution shifted right; each user selected a different score: 3, 5, 7, 8, 9, 10
4. Plot A: Do you see evidence of neighboring states showing similar trends in the "rise of CS"? Why or why not? 
    + Motivation: Test my own conclusions/interpretation and the plot's effectiveness
    + Responses: Split almost 50-50, but the majority of users noted exceptions and ambiguity
5. Plot A: On a scale of 1 to 10, how useful do you find this plot in answering our research questions (1 = not useful at all; 10 = extremely useful)?
    + Motivation: General visualization effectiveness
    + Responses: Mixed; two users did not find it helpful (scores of 3 and 4); two users found it fairly useful (scores of 7 and 8); two users gave it a perfect score (10)
6. Plot A: Please provide any additional feedback on plot A below (optional).
    + Motivation: Open-ended feedback/journaling 
    + Responses: Four users responded; one noted that the "when did CS become popular" question is not answered well by this plot; one mentioned that the choropleth metric was confusingly worded; one noted an unintended use of multiple state selection, which was buggy
7. Plot B: Do you think "the rise of CS" has varied across the four regions shown in this plot? Why or why not? 
    + Motivation: Test my own conclusions/interpretation and the plot's effectiveness
    + Responses: All but one user did not see regional differences
8. Plot B: On a scale of 1 to 10, how useful do you find this plot in answering our research questions (1 = not useful at all; 10 = extremely useful)?
    + Motivation: General visualization effectiveness
    + Responses: Positively received; one user reported 8; three users reported 9; two users reported 10.
9. Plot B: Please provide any additional feedback on plot B below (optional).
    + Motivation: Open-ended feedback/journaling 
    + Responses: Three users responded with generally positive feedback
10. If you could create a third plot (i.e., "Plot C") to visualize these data in a different way, what kind of plot would you create?
    + Motivation: Determine if the visualizations encouraged further "I wonder if..." questions
    + Responses: All six users responded; they suggested connecting the data to historical event timelines (e.g., advances in CS/technology), availability of CS degrees by institution, and animation to show change over time in the map


# Synthesis
## Conclusions from Final Evaluation

Before reviewing the results of the survey, I reasoned that my visualizations would be successful by the following criteria: 

* Users directly graded them as useful (questions 5 and 8).
* Users were engaged and clicked through more than a handful of states (question 2) and had well-developed follow-up questions (question 10).
* Users understood what the graphs were showing (question 3) and drew reasonable, evidence-based conclusions about the patterns in the graphs (questions 4 and 7).

BOOKMARK working on this 

One user helped me discover and fix a bug in my map dashboard: 

> I especially liked the ability to select multiple states and compare their trends over time. But when you select several states, it can be difficult to tell which trend line corresponds to each state.

When I first made the plot, I didn't realize that `altair` supports multiple selection by holding shift by default. In light of this, I decided to map state to the color aesthetic and add explicit support and acknowledgement of this feature. 

**Overall, the final evaluation study helped me realize that I had focused too much on making the map dashboard "feature rich" and too little on directly answering the questions that I was asking. Often, simpler and more direct visualizations are better, as evidenced by the clear user preference for the regions plot over the map dashboard.**

TODO Organize these quotes

> The gradient makes it hard to see the direction when close to 0%.

> Also, since the graph shows percentage changes, the number of CS degrees may differ greatly from state to state. Therefore, it is difficult to conclude that neighboring states show a similar trend.

> This suggests a regional component to the rise of CS (possibly related to shared economic, educational, and technology-sector characteristics). But the pattern is not perfect, since some neighboring states show noticeably different levels of growth.

> Well it's mixed. Your research question is two pronged: "when did CS become popular" and "how has its popularity varied geographically." I think Plot A can answer the latter to a degree, but not the former. There should be some timelapse, or at least the ability to see (Year 201X - Year 1984). Also, are we looking for a year when all the states turn red as the time that CS became popular? How are we defining popularity? As for geography, are we thinking in terms of metropolitan areas? political/cultural regions

> No, the trends look very similar. The proportion varying makes sense, as the plot goes Northeast > West > South > Midwest. That is just where the tech and business sectors are located in the United States.

> It is interesting that the number of CS degrees increased around 1985, when personal computers were becoming more widespread, and again around 2000, during the early growth of the Internet. After that, there was a period of decline, followed by another increase in recent years as AI has become more popular.

> I would like a historical timeline of major events in CS industry (dot com bubble burst, great recession, etc.) below Plot B to understand what might be driving the change in popularity.

> Maybe plotting an overall nation wide trend of raw number (not proportion) of CS degrees awarded, along with 5 of it's competitors. Would be interesting to see which all go up when CS goes down.

## Evolution of Project

The scope and goals of this project shifted over the course of the term. In module 1 when we selected our data source, I initially planned to present data from individual institutions (i.e., universities) to understand more fine-scale variation in CS over time. However, once I started working with the data, I decided to respect the recommendation to keep datasets below 5K rows to not overburden `altair`. In module 2, we defined more specific tasks for our visualizations. At first, I planned to integrate my plots into a dashboard such that the regions aggregation was manual (users clicked on states to define a region, which then populates a line plot). I scaled this back significantly and relied on predefined regions in order to be able to show the code, visualizations, and narrative all together (in this `qmd`) and simplify the workflow. In module 3, my evaluation approach changed slightly. I originally envisioned a more experimental evaluation (e.g., testing if users are pulling correct statistics from plots). However, anticipating a small sample size, I ultimately went with a qualitative evaluation and strove to make the survey relatively quick and easy to fill out. 

# Metadata

This document was rendered at `{python} datetime.now(ZoneInfo("America/New_York")).isoformat()`.